# This workflow will run tests using node and then publish a package to NPM when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Run the Build
        run: yarn run build
        env:
          CI: true
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.type != 'none'
        run: |
          echo "Success publishing new version: ${{ steps.publish.version }}"
        run: |
          echo "Old latest: ${{ steps.publish.old-version }}"
      - if: steps.publish.type == 'none'
        run: |
          echo "Failure publishing new version, no version change from old latest: ${{ steps.publish.old-version }}"
        run: exit 1
